@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}

@authHello = api/auth/hello
@authRegister = api/auth/register
@authLogin = api/auth/login
@authProfile = api/auth/profile
/* --------------------------------- VSCODE --------------------------------- */
# VSCODE

### @name hello
GET  http://{{host}}/{{authHello}}

### @name register
POST http://{{host}}/{{authRegister}}
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "password"
}

### @name login
POST http://{{host}}/{{authLogin}}
Content-Type: application/json

{
  "email": "demo@demo.com",
  "password": "password"
}

### @name profile
GET  http://{{host}}/{{authProfile}}

/* -------------------------------- INTELLIJ -------------------------------- */
# INTELLIJ